name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        timeout-minutes: 2
      - name: Lint
        run: npm run lint
        timeout-minutes: 1
      - name: Prepare environment
        uses: SpicyPizza/create-envfile@v2.0
        with:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      - name: Build
        run: npm run build --if-present
        timeout-minutes: 2

